# 0. Diagnóstico

**Objetivo del notebook:** ubicar el nivel de partida de cada estudiante en cuatro frentes — fundamentos de Python, estadística descriptiva, manipulación de datos con `pandas` y conceptos generales de Machine Learning — antes de iniciar la Unidad 1. No es un examen calificable: es un mapa de brechas que te sirve para calibrar el ritmo de las primeras sesiones.

### Estructura del proyecto
```
proyecto/
├── data/        # datasets: crudo y preprocesado
├── models/      # modelos entrenados y artefactos serializados (.pkl)
├── notebooks/   # los notebooks del módulo (este directorio, incluye 0_Diagnostic.ipynb)
└── output/      # resultados exportados (ej. Excel con predicciones)
```
Este notebook es autocontenido: no descarga ningún archivo externo ni escribe en `data/`, `models/` u `output/`. Todos los ejercicios usan datos generados en memoria.

### ¿Qué NO es este diagnóstico?
* Un examen con nota que afecta la calificación final.
* Un filtro de admisión al seminario.

### ¿Qué SÍ es?
* Una mirada honesta a dónde está parado cada estudiante hoy.
* Un insumo para calibrar el ritmo de las primeras sesiones del seminario.
* El punto de partida que se compara contra el cierre del seminario (Unidad 3).

### ¿Por qué un diagnóstico?
El seminario asume un nivel base en programación y estadística (ver `README.md` del proyecto). En la práctica, ese nivel es heterogéneo dentro de un mismo grupo. Detectarlo el primer día — y no en la Sesión 5, a mitad del módulo de modelamiento — permite reforzar lo necesario sin frenar al resto del grupo.

### Estructura del diagnóstico
| Bloque | Qué revisa | Formato |
|---|---|---|
| 1. Fundamentos de Python | Tipos de datos, estructuras de control, funciones | Ejercicios de código para completar (`# TODO`) |
| 2. Estadística descriptiva | Media, mediana, desviación estándar, dispersión | Cálculo guiado sobre una muestra pequeña |
| 3. Manipulación de datos (pandas) | Filtrado, `groupby`, manejo de nulos | Ejercicio sobre un dataset de muestra |
| 4. Conceptos de Machine Learning | Train/test, overfitting, clasificación vs. regresión, clustering | Preguntas de opción múltiple |
| 5. Autopercepción de herramientas | Nivel autopercibido en Python, SQL, Power BI, Estadística | Escala 1-5 |

Al final se consolida un **mapa de brechas por bloque**, con una referencia de nivel (básico / intermedio / avanzado).

### Configuración inicial

Antes de instalar o importar librerías, se valida cuál es el intérprete de Python (kernel) que está usando el notebook — la misma verificación que se hace en `1_GetData.ipynb`, para evitar errores cuando el kernel activo no corresponde al entorno virtual `analitica`.

In [1]:
## validación del Kernel seleccionado
import sys
print(sys.executable)

c:\Python\venvs\py312\Scripts\python.exe

Se importan las librerías necesarias. A diferencia de los notebooks siguientes, aquí no se usa `kagglehub`: no hay descarga de datos, todo el contenido se genera en memoria.
- `pandas`, `numpy`: manipulación de datos y cálculo numérico.
- `statistics`: funciones estadísticas básicas de la librería estándar (útil para verificar resultados "a mano").
- `matplotlib`: una única visualización simple en el Bloque 5.

In [2]:
import statistics
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

## Bloque 1 — Fundamentos de Python

Tres ejercicios cortos: tipos de datos, estructuras de control y funciones. Cada celda de código tiene uno o más `# TODO`: complétalos y ejecuta la celda. Los `assert` no imprimen nada si el resultado es correcto; si algo falla, verás un `AssertionError` señalando qué revisar.

### Ejercicio 1.1 — Tipos de datos
Completa las variables para que representen, en este orden: el nombre de un cliente (texto), su antigüedad en meses (entero), su cargo mensual (decimal) y si tiene contrato activo (booleano).

In [ ]:
# TODO: asigna un valor de cada tipo indicado
nombre_cliente: str = ...      # texto
antiguedad_meses: int = ...    # entero
cargo_mensual: float = ...     # decimal
contrato_activo: bool = ...    # booleano

# Autochequeo — no modificar
assert isinstance(nombre_cliente, str), "nombre_cliente debe ser texto (str)"
assert isinstance(antiguedad_meses, int), "antiguedad_meses debe ser un entero (int)"
assert isinstance(cargo_mensual, float), "cargo_mensual debe ser decimal (float)"
assert isinstance(contrato_activo, bool), "contrato_activo debe ser booleano (bool)"
print("Bloque 1.1 OK — tipos de datos correctos")

### Ejercicio 1.2 — Estructuras de control
Dada una lista de cargos mensuales, completa la función para que devuelva cuántos clientes tienen un cargo mayor a `umbral`.

In [ ]:
cargos = [19.9, 45.0, 70.35, 89.9, 20.1, 55.0, 100.2, 30.0]

def contar_sobre_umbral(valores: list[float], umbral: float) -> int:
    '''Cuenta cuántos valores de `valores` superan `umbral`.

    Args:
        valores: lista de cargos mensuales.
        umbral: valor de referencia.

    Returns:
        Número de valores estrictamente mayores a `umbral`.
    '''
    contador = 0
    # TODO: recorre `valores` con un for y usa un condicional (if)
    # para incrementar `contador` cuando corresponda
    ...
    return contador

resultado = contar_sobre_umbral(cargos, 50.0)

# Autochequeo — no modificar
assert resultado == 4, f"Se esperaban 4 clientes sobre el umbral, se obtuvo {resultado}"
print(f"Bloque 1.2 OK — {resultado} clientes con cargo mayor a 50.0")

### Ejercicio 1.3 — Funciones
Completa una función que reciba el cargo mensual y la antigüedad en meses, y devuelva el cargo total acumulado (`cargo_mensual * antiguedad_meses`).

In [ ]:
def calcular_cargo_total(cargo_mensual: float, antiguedad_meses: int) -> float:
    '''Calcula el cargo total acumulado de un cliente.

    Args:
        cargo_mensual: valor facturado cada mes.
        antiguedad_meses: número de meses de permanencia.

    Returns:
        Cargo total acumulado.
    '''
    # TODO: implementa el cálculo
    ...

total_cliente = calcular_cargo_total(cargo_mensual=70.35, antiguedad_meses=12)

# Autochequeo — no modificar
assert abs(total_cliente - 844.2) < 0.01, f"Se esperaba 844.2, se obtuvo {total_cliente}"
print(f"Bloque 1.3 OK — cargo total: {total_cliente}")

## Bloque 2 — Estadística descriptiva

Sobre una muestra pequeña de antigüedad de clientes (en meses), calcula las medidas de tendencia central y dispersión más comunes. Usa `statistics` o `numpy` — ambas son válidas; el objetivo es reconocer cuándo usar cada medida, no memorizar la sintaxis.

In [ ]:
antiguedad_muestra = [2, 5, 5, 8, 12, 12, 12, 15, 20, 34, 45, 60, 60, 61, 72]

# TODO: calcula cada medida sobre `antiguedad_muestra`
media = ...
mediana = ...
desviacion_estandar = ...
rango = ...  # máximo - mínimo

print(f"Media:              {media:.2f} meses")
print(f"Mediana:             {mediana:.2f} meses")
print(f"Desviación estándar: {desviacion_estandar:.2f} meses")
print(f"Rango:               {rango} meses")

**Pregunta orientadora:** la media y la mediana de esta muestra no coinciden. ¿Qué te dice eso sobre la forma de la distribución? Responde en un par de líneas en la celda siguiente (no se autoevalúa, es para discusión en clase).

_Tu respuesta:_

...

## Bloque 3 — Manipulación de datos con `pandas`

Se genera en memoria un dataset pequeño de pedidos (sin descarga externa) para practicar filtrado, `groupby` y manejo de nulos — las mismas operaciones que se usarán sobre el dataset Telco Customer Churn a partir de la Sesión 3.

In [3]:
datos_pedidos = {
    "pedido_id":  [1, 2, 3, 4, 5, 6, 7, 8],
    "categoria":  ["Internet", "Telefonía", "Internet", "TV", "Telefonía", "Internet", "TV", None],
    "monto":      [45.0, 20.0, 60.5, None, 25.0, 55.0, 30.0, 40.0],
    "region":     ["Norte", "Sur", "Norte", "Norte", "Sur", "Sur", "Norte", "Sur"],
}
df_pedidos = pd.DataFrame(datos_pedidos)
df_pedidos

   pedido_id  categoria  monto region
0          1   Internet   45.0  Norte
1          2  Telefonía   20.0    Sur
2          3   Internet   60.5  Norte
3          4         TV    NaN  Norte
4          5  Telefonía   25.0    Sur
5          6   Internet   55.0    Sur
6          7         TV   30.0  Norte
7          8        NaN   40.0    Sur

### Ejercicio 3.1 — Valores nulos
Identifica cuántos valores nulos hay por columna.

In [4]:
# TODO: cuenta los valores nulos por columna de df_pedidos
nulos_por_columna = df_pedidos.isnull().sum()
print(nulos_por_columna)

pedido_id    0
categoria    1
monto        1
region       0
dtype: int64

### Ejercicio 3.2 — Filtrado
Filtra los pedidos de la región "Norte" con `monto` mayor a 40 (ignora filas con `monto` nulo).

In [5]:
# TODO: filtra df_pedidos según las condiciones indicadas
pedidos_norte_altos = df_pedidos[df_pedidos["region"]=="Norte"]
pedidos_norte_altos

   pedido_id categoria  monto region
0          1  Internet   45.0  Norte
2          3  Internet   60.5  Norte
3          4        TV    NaN  Norte
6          7        TV   30.0  Norte

### Ejercicio 3.3 — `groupby`
Calcula el monto promedio por `categoria`, ignorando los valores nulos de `monto` (comportamiento por defecto de `pandas`).

In [9]:
# TODO: agrupa por categoria y calcula el promedio de monto
promedio_por_categoria = df_pedidos.groupby(["categoria"]).agg(suma=("monto","sum"), promedio=("monto","mean"))
promedio_por_categoria

            suma  promedio
categoria
Internet   160.5      53.5
TV          30.0      30.0
Telefonía   45.0      22.5

## Bloque 4 — Conceptos de Machine Learning (opción múltiple)

Cinco preguntas de opción múltiple sobre conceptos que se usarán a partir de la Unidad 2. No busques la respuesta antes de contestar — el valor de este bloque está en identificar qué no sabes todavía, no en acertar.

1. **¿Para qué se separa un dataset en `train` y `test`?**
<ol type="a">
   <li>Para acelerar el entrenamiento del modelo</li>
   <li>Para evaluar el modelo con datos que no vio durante el entrenamiento</li>
   <li>Para reducir el tamaño del archivo</li>
   <li>Es un paso opcional sin impacto en la evaluación</li>
</ol>

2. **El "overfitting" (sobreajuste) ocurre cuando...**
<ol type="a">
   <li>El modelo tarda demasiado en entrenar</li>
   <li>El modelo funciona igual de bien en train y en test</li>
   <li>El modelo aprende también el ruido de los datos de entrenamiento y generaliza mal en datos nuevos</li>
   <li>El dataset tiene demasiadas filas</li>
</ol>

3. **¿Cuál de estos problemas es de clasificación, no de regresión?**
<ol type="a">
   <li>Predecir el precio de una vivienda</li>
   <li>Predecir si un cliente cancelará su servicio (Sí/No)</li>
   <li>Predecir la temperatura de mañana</li>
   <li>Predecir las ventas del próximo trimestre</li>
</ol>

4. **El clustering (agrupamiento) es una técnica...**
<ol type="a">
   <li> Supervisada, que requiere una variable objetivo etiquetada</li>
   <li> No supervisada, que agrupa datos por similitud sin variable objetivo</li>
   <li> Exclusiva para series de tiempo</li>
   <li> Que solo funciona con datos categóricos</li>
</ol>

5. **La validación cruzada (cross-validation) sirve principalmente para...**
<ol type="a">
   <li>Reemplazar la necesidad de un conjunto de test</li>
   <li>Obtener una estimación más robusta del desempeño del modelo, usando varias particiones de los datos</li>
   <li>Aumentar artificialmente el tamaño del dataset</li>
   <li>Visualizar la matriz de confusión</li>
</ol>

In [ ]:
# TODO: registra tu respuesta a cada pregunta con la letra correspondiente ("a", "b", "c" o "d")
mis_respuestas = {
    "P1": None,
    "P2": None,
    "P3": None,
    "P4": None,
    "P5": None,
}

# Clave de respuestas — no se calcula un puntaje ni una "nota":
# el objetivo es que TÚ compares tu respuesta contra la clave y saques tus propias conclusiones.
respuestas_correctas = {"P1": "b", "P2": "c", "P3": "b", "P4": "b", "P5": "b"}

print("Compara tu respuesta contra la clave (no hay puntaje ni nivel calculado por el notebook):")
for k in respuestas_correctas:
    print(f"  {k}: tu respuesta = {mis_respuestas[k]}  |  clave = {respuestas_correctas[k]}")

## Bloque 5 — Autopercepción de herramientas

Sin buscar una respuesta "correcta": ubica tu nivel actual en cada herramienta, en una escala de 1 (nunca la he usado) a 5 (la uso con fluidez en proyectos reales).

In [ ]:
# TODO: califica cada herramienta de 1 a 5
autopercepcion = {
    "Python":      None,
    "SQL":         None,
    "Power BI":    None,
    "Estadística": None,
}

# Visualización simple del autodiagnóstico
etiquetas = list(autopercepcion.keys())
valores = [v if v is not None else 0 for v in autopercepcion.values()]

fig, ax = plt.subplots(figsize=(6, 3.5))
ax.barh(etiquetas, valores, color="#1E2761")
ax.set_xlim(0, 5)
ax.set_xlabel("Nivel autopercibido (1-5)")
ax.set_title("Autopercepción de herramientas")
plt.tight_layout()
plt.show()

## Resultados y mapa de brechas

Consolida en una sola tabla el estado de cada bloque: si los ejercicios de código se completaron (Bloques 1 y 3 corren sin `AssertionError` ni `Ellipsis` pendiente), si el Bloque 4 fue revisado contra la clave, y el promedio de autopercepción (Bloque 5). No es una calificación: es un mapa de qué tan avanzado está cada frente, para la conversación de nivelación al inicio del seminario.

In [ ]:
# Nota: si los Bloques 1 y 3 llegaron hasta aquí sin `AssertionError`,
# sus ejercicios ya están correctamente resueltos.
valores_autopercepcion = [v for v in autopercepcion.values() if v is not None]
promedio_autopercepcion = np.mean(valores_autopercepcion) if valores_autopercepcion else float("nan")

resumen = pd.DataFrame({
    "Bloque": [
        "1. Fundamentos de Python",
        "2. Estadística descriptiva",
        "3. Manipulación de datos (pandas)",
        "4. Conceptos de ML (quiz)",
        "5. Autopercepción de herramientas",
    ],
    "Resultado": [
        "Completado (asserts superados)",
        f"Media={media:.2f}, Mediana={mediana:.2f}, Desv.Est={desviacion_estandar:.2f}",
        "Completado (asserts superados)",
        "Revisado por ti — compara contra la clave del Bloque 4",
        f"Promedio {promedio_autopercepcion:.1f}/5" if not np.isnan(promedio_autopercepcion) else "Pendiente de completar",
    ],
})
resumen

### Siguiente paso

Este notebook no se entrega calificado: su valor está en la conversación de nivelación al inicio de la Sesión 1. Guarda el resumen anterior (captura de pantalla o exportación manual) para compartirlo si te lo solicitan.

A partir de aquí, el seminario continúa con la **Sesión 1** (fundamentos teóricos de estadística y modelización) y la **Sesión 2**, que arranca con `1_GetData.ipynb` sobre el caso de negocio Telco Customer Churn.